---
repos:
  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.10
        args: [--line-length=119]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.269"
    hooks:
      - id: ruff-autofix
        args: [--fix]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: name-tests-test

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-no-log-warn
      - id: python-use-type-annotations

  - repo: local
    # We do not use pre-commit/mirrors-mypy,
    # as it comes with opinionated defaults
    # (like --ignore-missing-imports)
    # and is difficult to configure to run
    # with the dependencies correctly installed.
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        language_version: python3.10
        additional_dependencies: ["mypy==1.3.0"]
        types: [python]
        # use require_serial so that script
        # is only called once per commit
        require_serial: true
        # Print the number of files as a sanity-check
        verbose: true
        args:
          - --ignore-missing-imports
          - --follow-imports=skip
          - --install-types
          - --non-interactive
          - --strict-optional
          - --disallow-any-generics