version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
filters:
  messages:
    (): 'pybot.customLogging.SlackMessageFilter'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    filters:
    - messages
    formatter: simple
    stream: ext://sys.stdout
loggers:
  sirbot:
    level: DEBUG
    propagate: true
  pyback:
    level: DEBUG
    propagate: true
  slack:
    level: DEBUG
    propagate: true
  urllib3:
    level: WARNING
    propagate: true
root:
  level: DEBUG
  handlers:
  - console
propagate: no