version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.3.0
  aws-ecs: circleci/aws-ecs@2.2.1
  docker: circleci/docker@0.5.1

workflows:
  build_test_deploy:
    jobs:
      - build_test

      # push new Docker image to Docker Hub
      - docker/publish:
          image: operationcode/pybot
          dockerfile: docker/Dockerfile
          tag: ${CIRCLE_BRANCH}
          after_build:
            - run:
                name: Tag and Push
                command: |
                  IMAGE_ID=operationcode/pybot
                  docker tag ${IMAGE_ID}:${CIRCLE_BRANCH} ${IMAGE_ID}:${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}
                  docker push ${IMAGE_ID}:${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}
          requires:
            - build_test
          filters:
            branches:
              only:
                - master
                - staging


      # push new Docker image to ECS
      - aws-ecr/build-and-push-image:
          repo: pybot
          tag: '${CIRCLE_BRANCH}'
          dockerfile: docker/Dockerfile
          requires:
            - build_test
          filters:
            branches:
              only:
                - staging
                - master

      # Update ECS task and service, then replace the current one
      - aws-ecs/deploy-service-update:
          family: 'pybot-${CIRCLE_BRANCH}'
          service-name: 'pybot-svc-${CIRCLE_BRANCH}'
          cluster-name: 'python-oc-services'
          container-image-name-updates: 'container=pybot,tag=${CIRCLE_BRANCH}'
          verify-revision-is-deployed: true
          requires:
            - aws-ecr/build-and-push-image
          filters:
            branches:
              only:
                - master
                - staging

jobs:
  build_test:
    docker:
      - image: circleci/python:3.7.1
        environment: # environment variables for primary container
          PIPENV_VENV_IN_PROJECT: "true"

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin

      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages

      - restore_cache:  # ensure this step occurs *before* installing dependencies
          keys:
            - v1-dependencies-{{ checksum "poetry.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Installing dependencies
          command: |
            pip install --upgrade pip
            pip install poetry
            poetry install

      - save_cache:
          key: v1-dependencies-{{ checksum "poetry.lock" }}
          paths:
            - "/home/circleci/.cache/pypoetry/virtualenvs"
            - ".venv"

      # Run tests
      - run:
          name: Run Tests
          command: |
            mkdir test-results
            poetry run pytest --junitxml=test-results/pytest/results.xml

      - store_test_results:
          path: test-results