---
version: '3.9'
services:
  pybot:
    image: pybot:latest
    container_name: pybot01
    ports:
      - "8010:8010"

  ngrok:
    image: wernight/ngrok:latest
    environment:
      - NGROK_PORT=pybot:8010
    ports:
      - "4040:4040"
