version: '3.9'
services:
  pybot:
    image: pybot:latest
    container_name: pybot01
    ports:
    - "5001:5001"

  ngrok:
    image: wernight/ngrok:latest
    environment:
    - NGROK_PORT=pybot:5001
    ports:
    - "4040:4040"
