---
version: '3.9'

services:
  pybot:
    container_name: oc-pybot
    restart: on-failure
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: uvicorn main:api -host 0.0.0.0 --port 5001 --reload --log-level 'debug'
    ports:
      - "5001:5001"
